### ISSUE TITLE
AEX-4: æternity wallet deep linking specification

### ISSUE THREAD

**Issue by shekhar-shubhendu** [aeternity/AEXs#108]
### Discussions-To: 

https://forum.aeternity.com/t/aex-4-aeternity-wallet-deep-linking-specification/3231

### Content URL

https://github.com/aeternity/AEXs/blob/master/AEXS/aex-4.md

**Comment by noandrea** [comment]
it was decided to withdraw the AEX and to work on an implementation when a use case arise.

@knarz can you please mark it as `stage/Withdraw`?
