### ISSUE TITLE
AEX-5: Inter-Wallet Communication

### ISSUE THREAD

**Issue by shekhar-shubhendu** [aeternity/AEXs#109]
### Discussions-To: 

https://forum.aeternity.com/t/aex-5-inter-wallet-communication/3371

### Content URL

https://github.com/aeternity/AEXs/blob/master/AEXS/aex-5.md

**Comment by davidyuk** [comment]
I'm asking to solve this: #119

**Comment by noandrea** [comment]
it was decided to withdraw the AEX and to work on an implementation when a use case arise.

@knarz can you please mark it as `stage/Withdraw`?

**Comment by knarz** [comment]
Please submit the corresponding pull requests as well
