### ISSUE TITLE
terms: account, identity, keypair

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#21]
In what cases each of them should be used? If we are talking about applications based on aeternity is this terms meaning same or not? Do we have any preferences or guidelines here?

In Base app we are using `account` mostly.

**Comment by knarz** [comment]
Identity is something more general than just an account or a keypair. I would use identity as a superset of keypairs and accounts. Many accounts and keypairs may make up one identity.

An account is an entry in the accounts tree and thus a singular identifiable thing.

One account might have more than one keypair, especially now with generalized accounts. As such, use keypair when describing cryptographic operations, that might as well be distinct from anything account related.
