### ISSUE TITLE
Fix compatibility with JSON RPC

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#24]
[JSON-RPC specification](https://www.jsonrpc.org/specification) doesn't say anything about `version` field in the root of response/requests objects. If it is needed to store protocol version it should use `params`, `result`, or method name to be compatible with JSON RPC.

I have seen the usage of `version` field in AEX-2 and AEX-5.

**Comment by shekhar-shubhendu** [comment]
@davidyuk we're trying to be as close to the state-channels JSON-RPC API which includes version field. you can find the example [here](https://github.com/aeternity/protocol/blob/master/node/api/examples/channels/json-rpc/sc_ws_basic_open_close.md).
The version field is as you guessed is needed to store protocol version.

**Comment by davidyuk** [comment]
Are AEX-2 and AEX-5 somehow connected to state-channels? If it is not, I think we can make a better decision here.

**Comment by shekhar-shubhendu** [comment]
it is not connected to but I would really like to keep the `protocol version` out of the method params as it does not makes sense to bind the `version` with the methods. If this breaks something we can find some other place to put it or we can remove it simply for now.

**Comment by shekhar-shubhendu** [comment]
@davidyuk on another thought and after discussing it with @nduchak we can do it this way:

wallet sends the supported version in the connection request (`wallet.request.connect`) only and if version mismatch or unsupported then SDK/aepp throws an error.
