### ISSUE TITLE
Extract JSON RPC definition/examples and explain its payload instead

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#25]
For example:

---
- `wallet.request.connect`: connection request sent by wallet containing an identifier that it wants to assign to the aepp/sdk. The generated identifier must be unique and must conform to the [UUID v4 standards](https://tools.ietf.org/html/rfc4122#page-14).

  json-rpc 2.0 structure:

  ```jsonc
  Request:
  {
    "jsonrpc": "2.0",
    "method": "wallet.request.connect",
    "params": {
       "id": "<unique_identifier_uuidv4>"
    },
    "version": 1
  }

  Response:
  {
    "jsonrpc": "2.0",
    "result": {
       "id": "<unique_identifier_uuidv4_as_request>",
       "name": "<aepp_name>"
    },
    "id": 1,
    "version": 1
  }
  ```
---

replace with something like this:

---
### wallet.request.connect
Connection request sent by wallet containing an identifier that it wants to assign to the aepp/sdk.

#### Parameters

`Object`
- `id` - The unique identifier, must conform to the [UUID v4 standards](https://tools.ietf.org/html/rfc4122#page-14)

#### Returns

`Object`
- `id` - The unique identifier as in request
- `name` - Tha name of aepp
---

I think it is less typo-prone and should make reading easier.

**Comment by shekhar-shubhendu** [comment]
@davidyuk we're already working on it as currently used `jsonc` is not compatible with documentation hub markdown. Will try to take your recommendation into account. Looks good to me.

**Comment by davidyuk** [comment]
Looks like this is resolved 👍
