### ISSUE TITLE
AEX-2: Simplify methods names

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#26]
Is it necessary to have a name of calling instance as a prefix for method name? I think it won't become more complicated if we drop them. Ex: `aepp.request.sign` => `request.sign`.

Also, does it have sense to rename methods that are already defined in sdk like `address` and `sign`?

**Comment by shekhar-shubhendu** [comment]
@davidyuk the prefix is used to identify(just by looking at the method name) who is invoking it.

**Comment by davidyuk** [comment]
If I'm writing a wallet part I know that all my RPC methods are invoked by aepp part, is it needed to have an addition hint?

**Comment by shekhar-shubhendu** [comment]
it is not really about the writing part. it is the understandability. By looking at the method name `aepp.request.sign`, although not very clear right now(will update the doc regarding this), I can come to the conclusion that the aepp/dapp is using it to request the signature while `request.sign` makes it more general. Currently, followed naming convention is used in the aeternity and is also chosen to have uniformity.

**Comment by davidyuk** [comment]
> By looking at the method name aepp.request.sign, ..., I can come to the conclusion that the aepp/dapp is using it to request the signature

You can get this also by looking at the header above, for example in AEX-2:

#### SDK/Aepp

- `method name`: ...

#### Wallet

- `method name`: ...

It is pretty clear. I still think that we should remove duplicate parts from method names.

> Currently, followed naming convention is used in the aeternity and is also chosen to have uniformity.

I have not seen it before, can you provide some links to discussions about it or existing implementations?

**Comment by shekhar-shubhendu** [comment]
I was talking more about people looking at the code directly or messages without looking at the AEX doc.

example from aeternity: https://github.com/aeternity/protocol/blob/master/node/api/examples/channels/json-rpc/sc_ws_basic_open_close.md#initiator-----node-1

I think we should move this discussion to the forum not many people check things here.

**Comment by davidyuk** [comment]
Let's imagine that somebody makes mapping of these RPC methods to some object in JS, like 
```
// on aepp side
const wallet = new Wallet(someTransport);
wallet.aeppGetAddress // will send a aepp.get.address request to wallet
```
`aeppGetAddress`, `getAddress`, `address`, what of these methods would be most understandable in this case? I beat that it is `getAddress` or `address` but definitely not `aeppGetAddress`. If `aeppGetAddress` is not the best in this case, then we shouldn't use it in RPC interface as well.

If you want to make it more accessible, you can make a wrapper around RPC interface that will use the best methods names as you think, AEX-2 doesn't limit this. Therefore in AEX-2 we can use method names precise explaining of a performing action in a short manner. I think method names from JS SDK fits the best in this case.

**Comment by davidyuk** [comment]
> example from aeternity: https://github.com/aeternity/protocol/blob/master/node/api/examples/channels/json-rpc/sc_ws_basic_open_close.md#initiator-----node-1

I don't think that state channels API is a good example because:
- they always using `channels` prefix, I don't see sense here as well, it could work as scoping of methods specific for state channels, but endpoint name that they are using already contains `channels` that means that all methods already connected to state channels
- they already using JSON RPC in a not compatible way (#24), maybe it was developed not very accurate, so we shouldn't copy made decisions without understanding

Do you know the reasoning behind method names of state channels API? Is it explained somewhere?

**Comment by davidyuk** [comment]
> I was talking more about people looking at the code directly or messages without looking at the AEX doc.

Prerequisite to work with AEX is to read AEX except for cases when it is implemented by some library. I think AEXs should be focused on developers that building an implementation of AEX-2 for some reason. We shouldn't spend time on cases like somebody unexpectedly opened a code of some library that built according to some AEX and starting to investigate it.

**Comment by davidyuk** [comment]
> I think we should move this discussion to the forum not many people check things here.

if you want, you can link the discussion on the forum to this issue and vice versa

> the issues section of this repository is an excellent place to discuss your proposal with the community (AEX-1)

**Comment by shekhar-shubhendu** [comment]
> Let's imagine that somebody makes mapping of these RPC methods to some object in JS, like
> 
> ```
> // on aepp side
> const wallet = new Wallet(someTransport);
> wallet.aeppGetAddress // will send a aepp.get.address request to wallet
> ```
> 
> `aeppGetAddress`, `getAddress`, `address`, what of these methods would be most understandable in this case? I beat that it is `getAddress` or `address` but definitely not `aeppGetAddress`. If `aeppGetAddress` is not the best in this case, then we shouldn't use it in RPC interface as well.
> 
> If you want to make it more accessible, you can make a wrapper around RPC interface that will use the best methods names as you think, AEX-2 doesn't limit this. Therefore in AEX-2 we can use method names precise explaining of a performing action in a short manner. I think method names from JS SDK fits the best in this case.

AEX-2 does not force method naming convention and only mentions JSON-RPC messages shared between parties. It is the responsibility of the developer to decide how he/she wants to structure the code and name their methods.

JSON-RPC messages in the AEX-2 do not follow the JS naming convention.

**Comment by davidyuk** [comment]
> AEX-2 does not force method naming convention and only mentions JSON-RPC messages shared between parties. It is the responsibility of the developer to decide how he/she wants to structure the code and name their methods.

Yes, it is true. But still, we can make JSON-RPC method names in AEX-2 and future standards as simple as possible. Why don't do it?

> JSON-RPC messages in the AEX-2 do not follow the JS naming convention.

It is not just JS naming convention it is more OOP. JSON-RPC correspond to that model and I think its method names should be compatible with it. Somebody will use JSON-RPC client that will make such mapping and he will get a super weird `wallet.aeppGetAddress`. By AEX-2 we can make it just `wallet.address` or `wallet.getAddress` that is more usual in this case.

**Comment by shekhar-shubhendu** [comment]
@davidyuk the method names(for me at least) seem simple and descriptive and all I can see here is a difference in perspective. the names described by you are good for JS method name but are not descriptive enough to qualify as JSON-RPC messages(as defined/used by aeternity).
Once the aeternity protocol decides to update the [naming convention](https://github.com/aeternity/protocol/tree/master/channels#terms) used I'll be happy to update the method name till then I don't see this discussion going anywhere.

**Comment by davidyuk** [comment]
Why `get.address` is not descriptive enough to qualify as JSON-RPC messages?

> used by aeternity

It is only used in state channels api, it should be accepted by the community to force it in AEXs

**Comment by davidyuk** [comment]
By the way, are you sure that you have applied `who - what - how` rule correctly? They have `solo` as an example of `how`. Do `address`, `sign`, or `network` can be `how`? Maybe `who` means object of some action instead of a subject? Applying this I have got:
```
aepp.get.address => address.get
aepp.request.sign => data.sign
aepp.update.network => network.set
wallet.request.connect => connection.open
wallet.get.network => network.get
wallet.update.address => address.set
wallet.broadcast.tx => transaction.broadcast
wallet.verify.tx => transaction.verify
wallet.disconnect.aepp => connection.close
```
I have to admit that it seems better than the current naming.

Why you propose to use dots as a separator of method name parts? As I see in [OFF-CHAIN.md](https://github.com/aeternity/protocol/blob/master/channels/OFF-CHAIN.md), [ON-CHAIN.md](https://github.com/aeternity/protocol/blob/master/channels/ON-CHAIN.md) they are using underscores.

**Comment by noandrea** [comment]
@AndreasGassmann @mradkov @mpowaga @nduchak @knarz 
can you add your input with the goal to resolve the issue?

**Comment by shekhar-shubhendu** [comment]
@noandrea can you set a deadline for requested parties for providing input too else this will remain open.

**Comment by mradkov** [comment]
I'm supporting @davidyuk's proposal here. I think its more readable this way.

**Comment by shekhar-shubhendu** [comment]
@davidyuk @mradkov can you please provide a brief description of what the naming scheme should be and how it benefits the overall readability than the current one. also please take a look at the current method and notification names and provide a corresponding list.

**Comment by davidyuk** [comment]
@shekhar-shubhendu I think I just have applied `who - what - how` rule in the right way. Can you respond on https://github.com/aeternity/AEXs/issues/26#issuecomment-498782629?
