### ISSUE TITLE
AEX-2: Drop identifiers

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#29]
Some transports like `postMessage` interface provide own identification mechanisms. That in the case of `postMessage` interface (`origin` field) even more secure that proposed solution, because of the `origin` field provided by a browser so can't be faked. This makes reasonable to make identifiers proposed by AEX-2 optional.

**Comment by shekhar-shubhendu** [comment]
Using different `identifiers` for different transport layer will break the uniformity and will be difficult to manage.

**Comment by davidyuk** [comment]
It means that AEX-2 trying to handle too much, let's make it simpler. We shouldn't ignore features with greater security because of our universal standards. Maybe we can extract identification into a separate standard and apply when it is necessary?

**Comment by shekhar-shubhendu** [comment]
AEX-2 is adding an identifier but you can always use the features provided by the `postMessage` API(or any transport layer) alongside it. I don't see how adding the identifier will break it.

**Comment by davidyuk** [comment]
https://github.com/aeternity/AEXs/issues/40#issuecomment-498747203 probably proves that identifiers are not needed at all or they should be reimplemented

**Comment by davidyuk** [comment]
> Defining the transport layer incl. connection set up between wallet and aepp is currently out of scope and will not be added to the AEX. https://github.com/aeternity/AEXs/issues/40#issuecomment-498956264

I was thinking that identifiers are made for one of the cases from #40. If it is "out of scope", then I can't find any reasoning for identification mechanics and proposing to drop it.

**Comment by davidyuk** [comment]
Solved in #57
