### ISSUE TITLE
AEX-2,5: What SDK means?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#36]
Is it JS SDK? I think 2, 5 AEXs should explain communication between instances (aepp <-> wallet, and wallet <-> wallet) without mentioning of the existing project that is supposed to implement this, otherwise, it gets more confusing. I think these AEXes should be explained in a way that makes possible to implement them without relying on existing SDK package.

**Comment by shekhar-shubhendu** [comment]
@davidyuk noted. cosmetic changes can be done anytime to the AEX (also via a pull request by anyone). I'll do this in maybe this sprint or else in the next.

**Comment by davidyuk** [comment]
Solved in #57
