### ISSUE TITLE
AEX-2: Issues list

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#38]
### Wallet methods

- ~~what is return value of `aepp.get.address` method?~~ extracted to #46
- ~~in what format tx should be passed to `aepp.request.sign` method? I see several options: hex string, an array of bytes, `tx_..` string, the current explanation is too ambiguous~~ extracted to #65
- ~~in what format tx returned from `aepp.request.sign` method?~~ extracted to #65
- [x] for what reason `aepp.request.sign` and other methods should return `id` received in arguments?

### Aepp methods
- ~~what is return value of `wallet.get.network` method?~~ extracted to #50
- ~~how aepp can use a list of connected account returned from `wallet.update.address` if it can't switch between them? We either should drop it or add a method for account switching.~~ extracted to #47
- ~~can `wallet.update.address` be simplified by extracting of getting a list of connected accounts into a separate method?~~ extracted to #48
- ~~`wallet.update.address` method should explain parameters explicitly, not only by providing an example~~ extracted to #45
- ~~for what reason~~ ~~in which cases `wallet.broadcast.tx` and `wallet.verify.tx` methods are necessary?~~ extracted to #63

### Common issues
- ~~add errors that can be thrown by method to explanation of every method~~ ~~remove errors explanations from `wallet.broadcast.tx`, `wallet.verify.tx` for consistency with other methods~~ extracted to #66
- ~~how `aepp.update.network` and `wallet.get.network` methods are supposed to work?~~ extracted to #50

**Comment by shekhar-shubhendu** [comment]
as these issues deal with syntactic changes and not the core functionality provided by the proposal, therefore, these will be added either in this sprint or the next. thanks for the contribution.

for some of the issues stated I suggest you to please re-read the proposal.

**Comment by davidyuk** [comment]
yes, but it can lead to breaking changes in AEX-2

**Comment by shekhar-shubhendu** [comment]
> yes, but it can lead to breaking changes in AEX-2

these will be handled with sample implementation on AEX finalization. No need to worry I think right now.

**Comment by davidyuk** [comment]
> for some of the issues stated I suggest you to please re-read the proposal

for which issues?

**Comment by shekhar-shubhendu** [comment]
> ### Wallet methods
> * [ ]  what is return value of `aepp.get.address` method?

Already part of the AEX. Please re-read.

> * [ ]  in what format tx should be passed to `aepp.request.sign` method? I see several options: hex string, an array of bytes, `tx_..` string, the current explanation is too ambiguous

Will be added.

> * [ ]  in what format tx returned from `aepp.request.sign` method?

Will be added. same as above.

> * [ ]  for what reason `aepp.request.sign` and other methods should return `id` received in arguments?

Already part of the AEX. Please re-read.

> 
> ### Aepp methods
> * [ ]  what is return value of `wallet.get.network` method?

Already part of the AEX. Please re-read.

> * [ ]  how aepp can use a list of connected account returned from `wallet.update.address` if it can't switch between them? We either should drop it or add a method for account switching.
> * [ ]  can `wallet.update.address` be simplified by extracting of getting a list of connected accounts into a separate method?

Not required.

> * [ ]  `wallet.update.address` method should explain parameters explicitly, not only by providing an example

Not required.

> * [ ]  for what reason `wallet.broadcast.tx` and `wallet.verify.tx` methods?

Already part of the AEX. Please re-read.

> 
> ### Common issues
> * [ ]  add errors that can be thrown by method to explanation of every method

Error explation are descriptive enough.

> * [ ]  how `aepp.update.network` and `wallet.get.network` methods are supposed to work?

Already part of the AEX. Please re-read.

**Comment by davidyuk** [comment]
> Will be added.

Can you explain it better than "Currently supported format: `tx_` string"? Maybe add a link to some document explaining what is `tx_` string? #34, #35

>> for what reason aepp.request.sign and other methods should return id received in arguments?

> Already part of the AEX. Please re-read.

I can't find, can you point to specific part?

>> for what reason wallet.broadcast.tx and wallet.verify.tx methods?

> Already part of the AEX. Please re-read.

Yes, I see them, in which cases they are necessary?

> Error explation are descriptive enough

So, let's remove errors explanations from `wallet.broadcast.tx`, `wallet.verify.tx` methods for consistency.

**Comment by davidyuk** [comment]
All unresolved issues are moved to separate issues
