### ISSUE TITLE
AEX-2: How wallet can determine that it was talking to some aepp before?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#39]
As I see, communication should start with sending of a random id by the wallet to aepp, and later aepp is identified by this id. What if the user has used some aepp before and give it some permissions, and when he opens it back does AEX-2 can identify this aepp as previously used? Or wallet and aepp developers should build one more identification mechanism on top of AEX-2?

**Comment by shekhar-shubhendu** [comment]
currently out of scope for this AEX. best would be to create a separate aex for this functionality

**Comment by davidyuk** [comment]
I think we should mention in AEX-2 that developers shouldn't rely on them as persistent and additional identification is needed for that.

**Comment by shekhar-shubhendu** [comment]
noted. but it is up to the developers how they want to use it. if they want it to be persistent and use them throughout they can very well choose too. the AEX proposal uses `id` to uniquely identify the sender and receiver of messages. The AEX2,5 do not deal with best practices and it is up to the community to decide.

**Comment by davidyuk** [comment]
> if they want it to be persistent and use them throughout they can very well choose too

> `wallet.request.connect`: connection request sent by the wallet containing an identifier that it wants to assign to the aepp/sdk

Don't it means that wallet should send a random identifier every time? Or you mean that wallet can somehow identify aepp by itself and then send the existing identifier? Do we need identifiers in AEX-2 if wallet can identify aepp by itself?

> The AEX2,5 do not deal with best practices and it is up to the community to decide.

Are you sure about the necessity of identifiers in AEX-2? If not why don't introduce them later?

**Comment by davidyuk** [comment]
So, this determination is not a part of AEX-2, I suppose that for this purpose should be used the domain of URL / postMessage origin or some other transport depending identifier.
