### ISSUE TITLE
AEX-5: Issues list

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#42]
> Wallet returns its current address and other account addresses it may help the SDK in getting signature for.

- [ ] For what reason wallet should return other accounts? How it can help in getting signatures?

https://github.com/aeternity/AEXs/blob/9e7a9360d8fb942ff32a4492deb2e289b51e3aff/AEXS/aex-5.md#proposed-process-with-inter-wallet-communication
- [ ] What is the difference between direct and indirect links?

| AEX-2 method names | AEX-5 method names |
|---|---|
| wallet.request.connect | wallet.channel.initiate |
| wallet.disconnect.aepp | wallet.channel.close |
| aepp.request.sign | wallet.sign.tx |
| wallet.broadcast.tx | wallet.request.broadcast |
- [ ] Why don't make names of these methods same? (excluding difference in wallet/aepp)

- [ ] AEX-5 mostly duplicates the functionality of AEX-2 I think we should unify them into AEX-2. So, if we want to connect two wallets, the master wallet should communicate with slave wallet as with aepp.

**Comment by shekhar-shubhendu** [comment]
this issue seems to be a reiteration of things that have been discussed extensively during the finalization of the AEX incl. the method names.

**Comment by davidyuk** [comment]
I think it is important to have them resolved explicitly and publicly. To be able to check how these decisions were made. Do you have links to discussions on these topics? Or we can start discussing them essentially.

**Comment by davidyuk** [comment]
I can't find any discussions in https://forum.aeternity.com/t/aex-5-inter-wallet-communication/3371

**Comment by marc0olo** [comment]
no longer relevant, AEX-2 and AEX-5 are both withdrawn. I am wondering if we should propose a new standard for wallet connections. seems like this has generally been a big pain in the past
