### ISSUE TITLE
Should be possible to explain AEXs in examples without explanations that cover them completely?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#45]
For instance, [Example Account Format](https://github.com/aeternity/AEXs/blob/aa8c1a6/AEXS/aex-2.md#parameters-6) introduces the `name` field that is not mentioned anywhere else.

**Comment by shekhar-shubhendu** [comment]
noted. will add a better explanation, rationale and intended usage.

**Comment by davidyuk** [comment]
Solved in #57
