### ISSUE TITLE
AEX-2: Make `aepp.get.address` method simplier

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#46]
JSON RPC supports return values of methods. Right now `aepp.get.address` is notification (without return value). And when this notification emitted by aepp, as I guess, the wallet should call `wallet.update.address` notification in advice. Straightforward usage of JSON RPC would be calling of `aepp.get.address` method and getting an address in reply, without introducing of `wallet.update.address` method and `error` method that is needed to return an error to aepp.

**Comment by davidyuk** [comment]
AEX-2 should have a separate method that returns the current address without making a subscription because subscriptions are not necessary for all applications, and simple address call should be easier to understand for beginners.

**Comment by shekhar-shubhendu** [comment]
i don't think it is much complicated to understand really.
having multiple methods that do the same thing will be more confusing for people.

**Comment by AndreasGassmann** [comment]
@davidyuk I agree that it would be simpler, but why not just add some good examples so beginners can simply copy/paste the code and it works?

**Comment by davidyuk** [comment]
@AndreasGassmann sure we can do that

I have one more point about this. If we are using transport when only an aepp can initiate a message exchange (like deep linking/qr codes) then a subscription for address won't have sense, because wallet won't be able to provide address updates. To have two methods and to say that `subscribe` won't be available is clearer than to define a new behavior of `subscribe` methods (that actually won't make a subscription in that case).

**Comment by marc0olo** [comment]
no longer relevant, AEX-2 is withdrawn. I am wondering if we should propose a new standard for wallet connections. seems like this has generally been a big pain in the past
