### ISSUE TITLE
AEX-2: How aepp can use a list of accounts returned from wallet.update.address?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#47]

**Comment by shekhar-shubhendu** [comment]
Please expand on the topic.

**Comment by davidyuk** [comment]
[`wallet.update.address`](https://github.com/aeternity/AEXs/blob/aa8c1a6/AEXS/aex-2.md#parameters-6) method provides a list of `connected` accounts. How aepp can use these connected accounts? Is it necessary to have it in standard?

**Comment by shekhar-shubhendu** [comment]
> [`wallet.update.address`](https://github.com/aeternity/AEXs/blob/aa8c1a6/AEXS/aex-2.md#parameters-6) method provides a list of `connected` accounts. How aepp can use these connected accounts? 

every connected wallet will return this list. this means that wallet does not hold the keys to these accounts but is connected to the wallet that does. this connection can either be 1-1 or via another wallet that it can forward sign request through.
getting signature for any of the connected account will be same as for current account and wallet will internally handle the request forwarding.

> Is it necessary to have it in standard?

yes. esp for aex-5 as we would not like to update aex-2 again when aex-5 is enabled.

**Comment by nduchak** [comment]
So the main idea is to allow AEPP to use all Wallet available accounts(Can prepare transaction not only for current Wallet account)?

**Comment by shekhar-shubhendu** [comment]
@nduchak yes.

**Comment by davidyuk** [comment]
Ok, this one resolved. I got stuck on this probably because of current Base app architecture.
