### ISSUE TITLE
AEX-2: Make account retrieving simpler

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#48]
I propose to implement two methods: one for getting a current account, and the other one for getting all accounts.

**Comment by davidyuk** [comment]
@shekhar-shubhendu how #57 resolves this issue?

**Comment by shekhar-shubhendu** [comment]
> I propose to implement two methods: one for getting a current account, and the other one for getting all accounts.

- for the first you can subscribe only to the `current` account.
- for the second you can subscribe to both `current` and `connected` accounts.

**Comment by davidyuk** [comment]
What meaning has a current account for aepp if it already has access to several accounts? Aepp can't ask wallet to change current account, but it can use any of them to sign a transaction. Looks that to know `current` account is not useful in that case. So, I propose to return only an object of accounts. If it contains only one account it means that it is "the current one" if not then aepp can show own account switcher or something similar.

**Comment by shekhar-shubhendu** [comment]
> > I propose to implement two methods: one for getting a current account, and the other one for getting all accounts.
> 
> * for the first you can subscribe only to the `current` account.
> * for the second you can subscribe to both `current` and `connected` accounts.

this will be kept as it is.



> What meaning has a current account for aepp if it already has access to several accounts? Aepp can't ask wallet to change current account, but it can use any of them to sign a transaction. Looks that to know `current` account is not useful in that case. So, I propose to return only an object of accounts. If it contains only one account it means that it is "the current one" if not then aepp can show own account switcher or something similar.

this will not be impl. as it only removes the distinction and does not add anything extra.

**Comment by marc0olo** [comment]
no longer relevant, AEX-2 is withdrawn. I am wondering if we should propose a new standard for wallet connections. seems like this has generally been a big pain in the past
