### ISSUE TITLE
AEX-2: Peers metadata

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#49]
In AEX-2 wallet and aepp exchanges with names as strings by calling of `wallet.request.connect` method. I think just name it is not enough. In Base app we are fetching [Web App Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) of aepp that we are taking to, we can do it without additional standards, just fetching manifest by aepp url.

I propose to make peers metadata a separate standard or use [Web App Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) objects instead of just app names.

**Comment by shekhar-shubhendu** [comment]
Does not makes sense to introduce and use a standard meant for Web Apps into a standard that can be used even by desktop apps.
If more fields are necessary please provide a list of them with a rationale behind each and we can discuss it here or in the forums.

**Comment by davidyuk** [comment]
> Does not makes sense to introduce and use a standard meant for Web Apps into a standard that can be used even by desktop apps.

I see your point, Web App Manifests has some properties that are incompatible in case of the native desktop apps like `display: "browser"`, `scope`, `serviceworker`, `start_utl`. But Web Manifests technically can handle that:
> Note also that implementations are free to ignore any member they do not recognize or support. (https://www.w3.org/TR/appmanifest/#extensibility)

> If more fields are necessary please provide a list of them with a rationale behind each and we can discuss it here or in the forums.

Let's add "icon" field. Icons are helpful because they make possible to recognize app faster than by reading its name, also most of the applications around us using them so it should be more user-friendly. In the worse case, we can communicate with aepp only by established connection, so it should be possible to pass an icon through it. Should we make possible to send icon in the response of `wallet.request.connect` as a base64-encoded string?

For the most popular use cases, this behavior looks strange. So I propose to describe metadata retrieving depending on the environment. Also, to suggest behavior explained above and "name" field to use in a case if none of the described cases is available.

**Comment by davidyuk** [comment]
Metadata in AEX-2 overlaps with https://github.com/aeternity/AEXs/pull/56, I think we should define it separately.

**Comment by shekhar-shubhendu** [comment]
yes i guess but this can be done later too when that aex is final and should not be breaking change for aex-2.
or let me know if you have an estimate on its completion and we can try to release both together?

**Comment by davidyuk** [comment]
@j28 what do you think about it?

**Comment by j28** [comment]
we should use the metadata standard from the aex draft.
