### ISSUE TITLE
AEX-2: In which case may be needed to update network from aepp?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#50]
As I see, currently wallet cat requests updation of its network details by `wallet.get.network`, then aepp should call `aepp.update.network`, passing only `networkId`. In which case may be needed to update network from aepp? More reasonable is to be able to get the current network id from the wallet, to be able to show, for example, special UI if the use on a test network.

Also, I'm not a fan of this idea because, I see that wallet is supposed to extract common functionality from aepps including network switcher, as well as managing of several account and so on.

Bytheway, that should happen if received `networkId` is unknown for a wallet?

Get network flow has the same issues as getting of address #46.

**Comment by shekhar-shubhendu** [comment]
Will be added to the rationale section and then let's discuss it in the forums.

**Comment by davidyuk** [comment]
@shekhar-shubhendu how #57 resolves this issue?

**Comment by shekhar-shubhendu** [comment]
as you can see this method has been removed from the aex-2 and we've added a notification for the wallet and app to inform the other party about change in network so that they can handle the requests appropriately.

wallet/app can inform other party about the network change but they can not enforce or trigger a network change.

**Comment by davidyuk** [comment]
Have you updated the rationale section as you promised in the message above? Is there any practical use cases when aepp need to inform wallet about network id? Isn't enough that network id is a part of the transaction that aepp sends to a wallet for signing?

**Comment by shekhar-shubhendu** [comment]
Let's assume the wallet wants to maintain a list of aepps it is/has connected to then it would be a nice feature for the wallet to show this detail there. this was the user can just open the wallet and see which aepp is on which network without going to check this on the aepp side.
if this info is part of the sign request then wallet can only say what was the network id of the last signed tx.

**Comment by davidyuk** [comment]
What if aepps resets network id to mainnet by default? Then the user will assume that aepp uses testnet but after opening it will appear to be connected to mainnet. It makes "without going to check this on the aepp side" a bad strategy.

https://github.com/aeternity/AEXs/pull/56 proposes to store supported networks in app metadata, it is better because wallet shouldn't open aepp to know it's network id.

**Comment by shekhar-shubhendu** [comment]
@davidyuk as suggested, this functionality will be removed
