### ISSUE TITLE
AEX-2: In which cases wallet.broadcast.tx method are necessary?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#63]

**Comment by shekhar-shubhendu** [comment]
`wallet.verify.tx`: was removed earlier. please update the issue accordingly.

`wallet.broadcast.tx`: if wallet has ability to create a transaction but can not broadcast.

**Comment by davidyuk** [comment]
In which cases wallet should create transaction by itself? I was thinking that only aepp can create a transaction and ask the wallet to sign it.

What is the purpose of `verify` option and what means transaction verification in general?

**Comment by shekhar-shubhendu** [comment]
wallet can create a transaction by itself(like spendtx) and also sign the transactions from aepps.
it might happen that a wallet does not have the ability to connect to the node or the node behind the wallet goes down then the wallet can propose the user to broadcast the tx via node behind the aepp.

**Comment by mradkov** [comment]
`wallet.broadcast.tx` is kind of edge case but is somehow a good-to-have feature in cases like @shekhar-shubhendu suggested.

**Comment by davidyuk** [comment]
> also sign the transactions from aepps

why it can't be handled by usual transaction sign flow?

Let's assume that wallet is not connected to any aepp and don't have access to any node then to send tokens wallet should ask the user to connect it to any aepp. Sounds like a bad UX. Also, I doubt that we can make this feature usable because aepp developer won't be interested to support edge cases like that.

But I know how we can make it much more flexible: to add a method for proxying of an arbitrary network request on both sides. This will allow wallet not only to broadcast signed transaction but also fetch balances, aens names and even access any third party api. How do you like it?

**Comment by shekhar-shubhendu** [comment]
> > also sign the transactions from aepps
> 
> why it can't be handled by usual transaction sign flow?
> 
> Let's assume that wallet is not connected to any aepp and don't have access to any node then to send tokens wallet should ask the user to connect it to any aepp. Sounds like a bad UX. Also, I doubt that we can make this feature usable because aepp developer won't be interested to support edge cases like that.
> 

the above feature will be kept to handle the use case as mentioned earlier

> But I know how we can make it much more flexible: to add a method for proxying of an arbitrary network request on both sides. This will allow wallet not only to broadcast signed transaction but also fetch balances, aens names and even access any third party api. How do you like it?

no, this will not be part of the aex-2. if required please provide a separate AEX.

**Comment by noandrea** [comment]
It is still under debate about where this functionality belongs and what is the correct implementation.
