### ISSUE TITLE
AEX-2: Add method for signing of personal message

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#64]
Related PR and discussion: https://github.com/aeternity/AEXs/pull/18

**Comment by shekhar-shubhendu** [comment]
we're aware of this. will add it to the aex-2.

**Comment by mradkov** [comment]
We are actually working on something regarding this in the waellet.

![0-02-05-5323d7e8b98b329c6e17cb49a1735e11061bdc764a27ee35582f7af8b4577c51_1c6d982c98ae1b](https://user-images.githubusercontent.com/13139371/62533249-e9bdca00-b84e-11e9-8ae6-3da6bc7bddfa.jpg)

**Comment by AndreasGassmann** [comment]
I would also add a method to sign and verify messages. AEX-8 will include the format on how the actual signing/verification that is done.

@mradkov Could you please comment in #18 on how you do your message signing? The reason we opened #18 was so all of our signed messages are compatible with each other and every wallet can verify messages signed by another one.

**Comment by davidyuk** [comment]
> add a method to sign and verify messages

In which cases verification is needed?

**Comment by mradkov** [comment]
> > add a method to sign and verify messages
> 
> In which cases verification is needed?

This is mostly for custom logic or verifications with signed messages. Some applications might use signed messages for authorization or for relaying transactions.

**Comment by davidyuk** [comment]
As I see verification can be done on aepp side, so it doesn't require an additional method in aepp-wallet communication

**Comment by marc0olo** [comment]
no longer relevant, AEX-2 is withdrawn. I am wondering if we should propose a new standard for wallet connections. seems like this has generally been a big pain in the past
