### ISSUE TITLE
AEX-2: Consistent explanations of exceptions that can be thrown by each method

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#66]

**Comment by shekhar-shubhendu** [comment]
this doesn't seem like an issue but only a cosmetic fix.
this will applied by removing the error details provided in some methods.

**Comment by davidyuk** [comment]
Why don't make AEX-2 more strict by setting possible exceptions for each method? Right now AEX-2 allows `aepp.subscribe.address` method to return `Broadcast Failed` exception, does it have sense?

**Comment by shekhar-shubhendu** [comment]
i think the error details are provided are enough and devs can follow through that.
adding error types for each method will only add redundancy.

> Right now AEX-2 allows aepp.subscribe.address method to return Broadcast Failed exception, does it have sense?

it will be removed and has been left there by mistake.

**Comment by AndreasGassmann** [comment]
Maybe I'm missing something, but there is already a list of possible errors included in AEX-2. Couldn't we simply also specify which methods can throw each of these errors?

**Comment by shekhar-shubhendu** [comment]
@AndreasGassmann the [meaning](https://github.com/aeternity/AEXs/blob/master/AEXS/aex-2.md#types-of-errors) part of the errors table defines exactly when the error must be thrown.
and if possible I would not go all the way defining a list of errors for each method as this not only creates redundancy but will also create room for typos, errors.
more generic the things are the better it would be in managing it.

**Comment by davidyuk** [comment]
> it will be removed and has been left there by mistake

I have misunderstood it, what will be removed?

**Comment by shekhar-shubhendu** [comment]
> > it will be removed and has been left there by mistake
> 
> I have misunderstood it, what will be removed?

please ignore.
