### ISSUE TITLE
AEX-2: Consider implementing the ability to connect two wallets

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#67]
AEX-5 mostly duplicates the functionality of AEX-2 I think we should unify them into AEX-2. So, if we want to connect two wallets, the "master" wallet should communicate with "slave" wallet as with aepp. (this proposal also mentioned in #42)

**Comment by shekhar-shubhendu** [comment]
it would be best to keep them different as aex-5 will does not treats 2 wallets differently as in base-aepp i.e. "master" and "slave".
both the connected wallets are treated same and can forward request to one another.
moreover, these two things are different functionalities and therefore should be kept separate.

**Comment by davidyuk** [comment]
Is it really needed to sign transactions in both directions? Can you provide some practical use cases? If it is needed, why they can't call `aepp.request.sign` from AEX-2?

**Comment by shekhar-shubhendu** [comment]
@emil-apeunit would be the best person to provide details here.

**Comment by AndreasGassmann** [comment]
While I agree that those 2 proposals are somewhat related, I think they should be kept separate simply because it's a completely different use case and I would also argue that AEX-2 is more important right now, AEX-5 is more something that could be used in the future. So we should try to move AEX-2 forward as fast as possible, and then adjust AEX-5 so it builds upon AEX-2.

**Comment by davidyuk** [comment]
I'm not sure that they are completely different use cases. For example, MyEtherWallet implements support of MetaMask in a way that MetaMask shouldn't implement any special interfaces for inner-wallet communication, and it works fine. Do we need additional interfaces for inner-wallet communication?

**Comment by AndreasGassmann** [comment]
Can't we just have another AEX later that extends this one? All I'm saying is that if we include this here, it will take longer. And as far as I'm aware, there is currently no concrete plan to use inter-wallet communication, so maybe let's just wait until there is and we can make decisions based on the limitations and use-cases we encounter then.

**Comment by davidyuk** [comment]
Ok, but in future, I will vote for not doing a separate standard for inter-wallet communication because AEX-2 already implements that.

**Comment by emil-apeunit** [comment]
@davidyuk I'm also very much in favor of keeping them separate, but AEX-5 can extend AEX-2 so that we don't have unnecessary duplicates.
