### ISSUE TITLE
Possible overlap between AEX-2 and AEX-7

### ISSUE THREAD

**Issue by noandrea** [aeternity/AEXs#70]
@AndreasGassmann @shekhar-shubhendu it appears to me that the two proposal are overlapping in one or more area, for example messages being supported.
Can you confirm that this is not the case?

**Comment by shekhar-shubhendu** [comment]
@noandrea no both are different. aex-7 deals with data serialization. aex-7 will be used in aex-4 deeplinking spec for the same purpose.

**Comment by AndreasGassmann** [comment]
I agree with @shekhar-shubhendu in that they are different. AEX-7 focusses on the format how messages can be exchanged.

**Comment by davidyuk** [comment]
Proposals are different, but both of them defines requests types and data serialization scheme. AEX-2 and AEX-7 definitely overlapping.

**Comment by noandrea** [comment]
after a debate on the issue in the aexpansion calls it was decided to change the nature of AEX-7 and to limit it to a serialization specification (only transport)
