### ISSUE TITLE
AEX-2: Consider to use predefined "Invalid params" exception instead of "Invalid Transaction", "Invalid Address"

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#71]
"Invalid Transaction" and "Invalid Address" exceptions is a special case of ["Invalid params"](https://www.jsonrpc.org/specification#error_object), do we need to handle them separately?

That should aepp sent in response if addresses are correct but they sent in an array instead of object?

**Comment by noandrea** [comment]
please provide a pr with the changes you want and close the issue

**Comment by davidyuk** [comment]
"Invalid address" got removed recently. "Invalid transaction" error should be used in obvious use cases, like when the number of arguments or their JSON type doesn't match. "Invalid transaction"  may be useful if it would indicate that the internal structure of the transaction is broken, to distinguish it with a case when `transaction.sign` received a number instead of a string.
