### ISSUE TITLE
AEX-2: Should all words in error messages be capitalized?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#72]
As I see error messages of JSON-RPC specification uses capital letters only in the first word and words that mean entities defined there (like Request), maybe we should do the same instead of making all words starting with a capital letter?

**Comment by davidyuk** [comment]
Almost fixed: https://github.com/aeternity/AEXs/pull/93/files#r332043248

**Comment by noandrea** [comment]
please provide a pr with the changes you want and close the issue

**Comment by davidyuk** [comment]
done, I will close it when #97 will be merged
