### ISSUE TITLE
AEX-2: Implement a separate method for unsubscription

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#73]
Calling `aepp.subscribe.address({ type: 'unsubscribe', value: 'current' })`, in other words to call subscribe method for unsubscription looks illogical.

**Comment by noandrea** [comment]
please provide a pr with the changes you want and close the issue

**Comment by marc0olo** [comment]
no longer relevant, AEX-2 is withdrawn. I am wondering if we should propose a new standard for wallet connections. seems like this has generally been a big pain in the past
