### ISSUE TITLE
AEX-4: Add `web+` prefix to be compatible with registerProtocolHandler

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#76]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler#Permitted_schemes
This proposal is inspired by [SEP-0007](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0007.md#security-best-practices-for-compliance-with-this-sep)

**Comment by shekhar-shubhendu** [comment]
👍

**Comment by marc0olo** [comment]
no longer relevant, AEX-4 is withdrawn
