### ISSUE TITLE
AEX-4: Why it defines two scheme names?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#78]
From what I found, [Bitcoin](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki#abnf-grammar), [Ethereum](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-831.md#syntax), [Stellar](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0007.md#specification) are using a single name for URI schemas, why do we need two names (`ae` and `aeternity`)? From my point of view, it makes development more complicated, each wallet should support both of them.

What if some `aeternity:` call failed, should aepp in that case try `ae:` scheme? What if the environment (like registerProtocolHandler) is asking confirmation for adding schema handler and the user agreed for the first one but declined the second? The single scheme will help to avoid such confusing situations.

**Comment by shekhar-shubhendu** [comment]
it is still a draft. the discussion is open on which one(or both) to use.
the final version will have a single scheme.

**Comment by davidyuk** [comment]
I have been asked to review it. I'm also thinking that it is not very efficient to review draft AEXs.

I think that we should use `aeternity:`.

**Comment by marc0olo** [comment]
no longer relevant, AEX-4 is withdrawn
