### ISSUE TITLE
AEX-4: Add status callback parameter

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#80]
As proposed in https://hackmd.io/@0GocXL2UTk-75Bt3XDppsA/BJObJntjQ?type=view#3-Wallet-app-opens-the-deep-link-to-the-source-app

It makes easier for aepp to understand what happened if the request didn't succeed.

**Comment by marc0olo** [comment]
no longer relevant, AEX-4 is withdrawn
