### ISSUE TITLE
AEX-4: it shows an address that exists in blockchain or user's accounts?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#81]
In the 2nd step, "Check if the address exists or not" this will check address existence in the user's accounts or that address exists in blockchain?

As I understand `schema:address` means an intention to send some tokens in Bitcoin and Ethereum, not just account opening, I think we shouldn't break that semantic in this proposal. It can be used in cases like if some charity is collecting donations without exact amounts of tokens to send. Also, the wallet shouldn't check account existance, because that charity can generate a new address each time to track user conversion.

In the 4th step, maybe `account not found` shouldn't be in quotes because we are not expecting the exact message but some message that explains this?

**Comment by marc0olo** [comment]
no longer relevant, AEX-4 is withdrawn
