### ISSUE TITLE
AEX-4: Define what is amount

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#84]
Example in [BIP-0021](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki#transfer-amountsize). One more example: [EIP-681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md#syntax) is more flexible than BIP-0021 and this AEX, it defines scientific notation and an ability to send amounts of tokens on top of ethereum.

**Comment by marc0olo** [comment]
no longer relevant, AEX-4 is withdrawn
