### ISSUE TITLE
AEX-4: Clean up references

### ISSUE THREAD

**Issue by davidyuk** [aeternity/AEXs#91]
I can't get how
https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0072.mediawiki
are connected to AEX-4.

**Comment by shekhar-shubhendu** [comment]
If you're unable to understand then please open an issue stating the same.
The title `Clean up references` is out of context.

**Comment by davidyuk** [comment]
If you can't explain it then I propose to remove them 🤷‍♀️
